name: Build, Test and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Install dependencies and Build 🔧 
        run: |
          cd agile
          npm ci
          npm run build

      - name: Run tests 🧪
        run: npm run test

      - name: Deploy 🚀
        run: |
          npm run deploy
          git add out/
          git commit -m "Deploy to GitHub Pages"
          git push origin HEAD:gh-pages
