name: Build and Deploy
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v2.3.1

      - name: Install and Build 🔧 # This example project uses npm. Replace with yarn if you use yarn.
        run: |
          cd agile
          npm install
          npm run build

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.5 # This is for GitHub Pages. If you're using Vercel or another service, you'll need a different action.
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: agile/out # The folder the action should deploy.
