name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Detect package manager
        id: detect-package-manager
        run: |
          if [ -f "${{ github.workspace }}/Final_Project/yarn.lock" ]; then
            echo "manager=yarn" >> $GITHUB_ENV
            echo "command=install" >> $GITHUB_ENV
            echo "runner=yarn" >> $GITHUB_ENV
            exit 0
          elif [ -f "${{ github.workspace }}/Final_Project/package.json" ]; then
            echo "manager=npm" >> $GITHUB_ENV
            echo "command=ci" >> $GITHUB_ENV
            echo "runner=npx --no-install" >> $GITHUB_ENV
            exit 0
          else
            echo "Unable to determine package manager"
            exit 1
          fi

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
          cache: ${{ env.manager }}

      - name: Setup Pages
        uses: actions/configure-pages@v3
        with:
          static_site_generator: next

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: |
            Final_Project/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('Final_Project/**/package-lock.json', 'Final_Project/**/yarn.lock') }}-${{ hashFiles('Final_Project/**.[jt]s', 'Final_Project/**.[jt]sx') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('Final_Project/**/package-lock.json', 'Final_Project/**/yarn.lock') }}-

      - name: Install dependencies
        run: cd Final_Project && ${{ env.manager }} ${{ env.command }}

      - name: Build with Next.js
        run: cd Final_Project && ${{ env.runner }} next build

      - name: Static HTML export with Next.js
        run: cd Final_Project && ${{ env.runner }} next export

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: NextJSBuild
          path: ./Final_Project/out

  deploy:
    environment:
      name: github-pages
      url: https://jcardona321.github.io/Final_Project/
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: NextJSBuild

      - name: Deploy to GitHub Pages
        id: deployment
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.NEW_SECRET }}
          publish_dir: ./NextJSBuild
          publish_branch: gh-pages
